spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  
  # Completely disable mail in development
  mail:
    host: 
    port: 0
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration
  
logging:
  level:
    dev.joeis.lombriculturaedenshop: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
