spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    dev.joeis.lombriculturaedenshop: INFO
    org.springframework: WARN
  file:
    name: /var/log/lombriculturaedenshop/application.log
    max-size: 10MB
    max-history: 30
